# Generated by Django 4.2.2 on 2023-08-11 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_alter_user_followers_alter_user_following'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['id']},
        ),
    ]
