# Generated by Django 4.2.2 on 2023-07-03 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bid_category_listing_comment_bid_origin_bid_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='origin',
            new_name='target_listing',
        ),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='listings', to='auctions.category'),
        ),
    ]
