# Generated by Django 4.2.2 on 2023-07-07 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_rename_origin_bid_target_listing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='target_listing',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='auctions.listing'),
        ),
    ]
