# Generated by Django 4.2.2 on 2023-07-09 09:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_alter_bid_created_at_alter_comment_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='in_watchlist',
            field=models.ManyToManyField(related_name='watched_listings', to=settings.AUTH_USER_MODEL),
        ),
    ]
