# Generated by Django 4.2.2 on 2023-07-09 09:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_listing_in_watchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='in_watchlist',
            field=models.ManyToManyField(blank=True, related_name='watched_listings', to=settings.AUTH_USER_MODEL),
        ),
    ]
