# Generated by Django 4.2.2 on 2023-07-09 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_alter_listing_in_watchlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='in_watchlist',
            new_name='watched_users',
        ),
    ]
