# Generated by Django 4.2.2 on 2023-07-09 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_rename_in_watchlist_listing_watched_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='is_in_watchlist',
        ),
    ]
