# Generated by Django 4.2.2 on 2023-10-12 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costrecord',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='costs', to='auditor.costcategory'),
        ),
    ]
