# Generated by Django 4.2.2 on 2023-12-16 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditor', '0002_alter_costrecord_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='costrecord',
            name='template',
            field=models.BooleanField(default=False),
        ),
    ]
