# Generated by Django 4.2.2 on 2023-12-18 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auditor', '0003_costrecord_template'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='costrecord',
            name='categories',
        ),
        migrations.AddField(
            model_name='costrecord',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='costs', to='auditor.costcategory'),
        ),
    ]
