# Generated by Django 4.2.2 on 2023-12-21 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditor', '0004_remove_costrecord_categories_costrecord_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='costcategory',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
